### ISSUE TITLE
[CRITERIA]

### ISSUE THREAD

**Issue by sjvrijn** [rseng/software#107]
## Repository 
https://github.com/sjvrijn/mf2

## Criteria
 - [x] criteria-RSE-absence
 - [x] criteria-RSE-citation
 - [x] criteria-RSE-domain-intention
 - [ ] criteria-RSE-question-intention
 - [x] criteria-RSE-research-intention
 - [x] criteria-RSE-usage

**Comment by vsoch** [comment]
Thank you @sjvrijn!
