### ISSUE TITLE
[CRITERIA]

### ISSUE THREAD

**Issue by s-sajid-ali** [rseng/software#52]
## Repository 
https://github.com/spack/spack

## Criteria
 - [x] criteria-RSE-absence
 - [x] criteria-RSE-citation
 - [ ] criteria-RSE-domain-intention
 - [ ] criteria-RSE-question-intention
 - [x] criteria-RSE-research-intention
 - [x] criteria-RSE-usage

## Comments

While it was intended to simplify software deployment at hpc centers, it's not restricted to that aim so I'm unsure if I would classify it as "intended for research" as it was built for it, but now it can be used elsewhere too.

**Comment by vsoch** [comment]
Woohoo thanks @s-sajid-ali ! If you want to annotate taxonomy items too (I suppose this one is easy... package management!) that is just one click too, same deal :)  https://rseng.github.io/software/repository/github/spack/spack/annotate-taxonomy/

I'll post it in slack in case you don't see here!
