### ISSUE TITLE
[TAXONOMY]

### ISSUE THREAD

**Issue by s-sajid-ali** [rseng/software#54]
## Repository 
https://github.com/spack/spack

## Taxonomy
 - [x] RSE-taxonomy-ide-research
 - [x] RSE-taxonomy-provenance-metadata-tools
 - [x] RSE-taxonomy-package-management

**Comment by vsoch** [comment]
Looks like the PR didn't trigger - I'll need to debug this one! Sorry about that @s-sajid-ali!
